#ifndef GAME_OF_LIFE_GLOBAL_MACROS_H
#define GAME_OF_LIFE_GLOBAL_MACROS_H

#define WINDOW_WIDTH 1440
#define WINDOW_HEIGHT 810
#define GRID_SIZE 30
#define DEAD_CELL_COLOR sf::Color(128, 128, 128)
#define LIVE_CELL_COLOR sf::Color::Red
#define SLEEP_DURATION 750

#endif
